#!/usr/bin/env bash
set -euo pipefail

# Run criterion benchmarks, append results to CSV history, and generate benchmarks.md.
# Usage:
#   ./scripts/bench-history.sh              # defaults to bench-history.csv
#   ./scripts/bench-history.sh results.csv  # custom output file

HISTORY_FILE="${1:-bench-history.csv}"
BENCHMARKS_MD="benchmarks.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Create header if file doesn't exist
if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,estimate_ns" > "$HISTORY_FILE"
fi

echo "╔══════════════════════════════════════════╗"
echo "║       impetus benchmark suite            ║"
echo "╠══════════════════════════════════════════╣"
echo "║  commit: $COMMIT                          ║"
echo "║  branch: $BRANCH                            ║"
echo "║  date:   $TIMESTAMP   ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Run benchmarks and capture output, stripping ANSI escape codes
BENCH_OUTPUT=$(cargo bench --bench simulation 2>&1 | sed 's/\x1b\[[0-9;]*m//g')

# Show full output
echo "$BENCH_OUTPUT"
echo ""

# Collect results for CSV and markdown
declare -a BENCH_NAMES=()
declare -a BENCH_NS=()
declare -a BENCH_DISPLAY=()

PREV_LINE=""
while IFS= read -r line; do
    if [[ "$line" == *"time:"*"["* ]]; then
        BENCH_NAME=$(echo "$line" | sed -E 's/[[:space:]]*time:.*//' | xargs)
        if [ -z "$BENCH_NAME" ]; then
            BENCH_NAME=$(echo "$PREV_LINE" | xargs)
        fi

        VALS=$(echo "$line" | sed -E 's/.*\[(.+)\]/\1/')
        MEDIAN=$(echo "$VALS" | awk '{print $3}')
        UNIT=$(echo "$VALS" | awk '{print $4}')

        # Normalize to nanoseconds
        case "$UNIT" in
            ps)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 / 1000}') ;;
            ns)  NS="$MEDIAN" ;;
            µs|us)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000}') ;;
            ms)  NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000000}') ;;
            s)   NS=$(echo "$MEDIAN" | awk '{printf "%.4f", $1 * 1000000000}') ;;
            *)   NS="$MEDIAN" ;;
        esac

        # Human-readable display value
        DISPLAY="${MEDIAN} ${UNIT}"

        echo "${TIMESTAMP},${COMMIT},${BRANCH},${BENCH_NAME},${NS}" >> "$HISTORY_FILE"
        BENCH_NAMES+=("$BENCH_NAME")
        BENCH_NS+=("$NS")
        BENCH_DISPLAY+=("$DISPLAY")
    fi
    PREV_LINE="$line"
done <<< "$BENCH_OUTPUT"

COUNT=${#BENCH_NAMES[@]}

# Generate benchmarks.md
{
    echo "# Benchmarks"
    echo ""
    echo "Latest run: **${TIMESTAMP}** — commit \`${COMMIT}\` on \`${BRANCH}\`"
    echo ""

    CURRENT_GROUP=""
    for i in $(seq 0 $((COUNT - 1))); do
        NAME="${BENCH_NAMES[$i]}"
        GROUP=$(echo "$NAME" | cut -d'/' -f1)
        BENCH=$(echo "$NAME" | cut -d'/' -f2)

        if [ "$GROUP" != "$CURRENT_GROUP" ]; then
            if [ -n "$CURRENT_GROUP" ]; then
                echo ""
            fi
            echo "## ${GROUP}"
            echo ""
            echo "| Benchmark | Time |"
            echo "|-----------|------|"
            CURRENT_GROUP="$GROUP"
        fi

        echo "| \`${BENCH}\` | ${BENCH_DISPLAY[$i]} |"
    done
    echo ""
    echo "---"
    echo ""
    echo "Generated by \`./scripts/bench-history.sh\`. History in \`bench-history.csv\`."
} > "$BENCHMARKS_MD"

echo "════════════════════════════════════════════"
echo "  ${COUNT} benchmarks recorded"
echo "  CSV:      ${HISTORY_FILE}"
echo "  Markdown: ${BENCHMARKS_MD}"
echo "════════════════════════════════════════════"
